### ISSUE TITLE
Error: Unique

### ISSUE THREAD

**Issue by MinIsMin** [DarkRedemption/darksdankdata#79] opened 2016-09-17 11:55 UTC
When starting the server, the following occurs:

DDD[Error]: Could not insert into table ddd_map_id!
        Error was:column map_name is not unique

When players (also bot) join:

 DDD[Error]: Could not insert into table ddd_player_id!
        Error was:column steam_id is not unique
(09/17/16 01:56:03 PM) DDD[Error]: Could not insert into table ddd_aggregate_stats!
        Error was:PRIMARY KEY must be unique

Another lua error:

[ULib] addons/dataprogresss/lua/ddd/main/database/tables/sv_aggregatestats.lua:321: attempt to concatenate local 'playerId' (a userdata value)
1. getRounds - addons/dataprogresss/lua/ddd/main/database/tables/sv_aggregatestats.lua:321
   1. incrementRounds - addons/dataprogresss/lua/ddd/main/database/tables/sv_aggregatestats.lua:376
   2. trackPlayerRoles - addons/dataprogresss/lua/ddd/main/hooks/sv_hooks.lua:63
      1. fn - addons/dataprogresss/lua/ddd/main/hooks/sv_hooks.lua:70
      2. Call - lua/ulib/shared/hook.lua:110
      3. unknown - gamemodes/terrortown/gamemode/init.lua:694

Timer Failed! [prep2begin][@gamemodes/terrortown/gamemode/init.lua (line 494)]

**Comment by DarkRedemption** [comment] 2016-09-17 12:42
use the latest 0.2.0-SNAPSHOT version. I think there were two issues I resolved in that, and the aggregate stats problem may be one of them. That or you have to run ddd_recalculate. I didn't update the release since I didn't have any other users until now that I knew of.

The MapId issue  is a duplicate of a known issue that isn't an actual problem; it's just a cleanliness thing. Mapnames are added into DDD to link the name with a unique ID. If the map already exists, you get that error because it doesn't check if it does at the moment. It won't cause any issues with functionality. Same with players and bots, which are saved by SteamID. It tries to add them, but they already exist. Since it causes no runtime problems, it's low priority to check first.

Make sure nothing else weird is happening by making a local test server (if this server you're running it on isn't) and running my GUnit tests. https://github.com/darkredemption/gunit

**Comment by DarkRedemption** [comment] 2016-09-17 12:52
Partial duplicate of #13 and #35

**Comment by DarkRedemption** [comment] 2016-09-17 12:59
Crap. I never pushed my 0.2.0-SNAPSHOT version. Give me a few minutes, I'll try to do that now.

**Comment by MinIsMin** [comment] 2016-09-17 14:00
Now trying with 0.2.0 - unique errors stay.

When accessing !dank:
[ERROR] addons/dankdata/lua/ddd/main/gui/rank/cl_overall.lua:25: bad argument #1 to 'pairs' (table expected, got number)
1. pairs - [C]:-1
   1. populateWithOverallEnemyKd - addons/dankdata/lua/ddd/main/gui/rank/cl_overall.lua:25
   2. updateListView - addons/dankdata/lua/ddd/main/gui/rank/cl_overall.lua:46
      1. OnSelect - addons/dankdata/lua/ddd/main/gui/rank/cl_overall.lua:77
      2. ChooseOption - lua/vgui/dcombobox.lua:108
      3. ChooseOptionID - lua/vgui/dcombobox.lua:118
      4. createOverallTab - addons/dankdata/lua/ddd/main/gui/rank/cl_overall.lua:81
         1. func - addons/dankdata/lua/ddd/main/gui/cl_mainpanel.lua:32
         2. unknown - lua/includes/extensions/net.lua:32

When buying a non-default TTT shop item:

[ULib] addons/dankdata/lua/ddd/main/database/tables/sv_aggregatestats.lua:437: attempt to concatenate a nil value
1. getItemPurchases - addons/dankdata/lua/ddd/main/database/tables/sv_aggregatestats.lua:437
   1. incrementItemPurchases - addons/dankdata/lua/ddd/main/database/tables/sv_aggregatestats.lua:500
   2. trackPurchases - addons/dankdata/lua/ddd/main/hooks/sv_hooks.lua:24
      1. fn - addons/dankdata/lua/ddd/main/hooks/sv_hooks.lua:33
      2. Call - lua/ulib/shared/hook.lua:110
      3. unknown - gamemodes/terrortown/gamemode/weaponry.lua:421
      4. unknown - lua/includes/modules/concommand.lua:54

**Comment by haste-jeff** [comment] 2016-09-17 14:08
I'll have a look when I get home with a fresh database. I expected non-vanilla items might be broken.

Run the GUnit tests. It may tell us more.

**Comment by DarkRedemption** [comment] 2016-09-17 14:09
I'll have a look when I get home. Try running the GUnit tests and see if they work.

**Comment by MinIsMin** [comment] 2016-09-17 14:25
When server starts:

[ERROR] lua/../addons/gwhat/lua/gunit/main/testengine/sv_test.lua:63: attempt to                                                                                         index a string value with bad key ('specs' is not part of the string library)
1. error - [C]:-1
   1. __index - lua/includes/extensions/string.lua:310
   2. addSpec - lua/../addons/gwhat/lua/gunit/main/testengine/sv_test.lua:63
      1. unknown - lua/../lua/autorun/server/wdsa/test.lua:9
      2. include - [C]:-1
      3. includeTests - addons/gwhat/lua/gunit/main/testengine/sv_load.lua:68
      4. includeTests - addons/gwhat/lua/gunit/main/testengine/sv_load.lua:78
         1. includeTests - addons/gwhat/lua/gunit/main/testengine/sv_load.lua:78
         2. includeTests - addons/gwhat/lua/gunit/main/testengine/sv_load.lua:7                                                                                        8
         3. load - addons/gwhat/lua/gunit/main/testengine/sv_load.lua:100
         4. unknown - lua/autorun/server/we.lua:6

[ERROR] lua/../addons/gwhat/lua/gunit/main/testengine/sv_test.lua:150: table index is nil
1. addProjectNameToTable - lua/../addons/gwhat/lua/gunit/main/testengine/sv_test.lua:150
   1. new - lua/../addons/gwhat/lua/gunit/main/testengine/sv_test.lua:176
   2. unknown - lua/autorun/server/test.lua:2

[ERROR] lua/../addons/gwhat/lua/gunit/main/testengine/sv_test.lua:63: attempt to index a string value with bad key ('specs' is not part of the string library)
1. error - [C]:-1
   1. __index - lua/includes/extensions/string.lua:310
   2. addSpec - lua/../addons/gwhat/lua/gunit/main/testengine/sv_test.lua:63
      1. unknown - lua/../lua/autorun/server/test.lua:9
      2. include - [C]:-1
      3. includeTests - addons/gwhat/lua/gunit/main/testengine/sv_load.lua:68
      4. includeTests - addons/gwhat/lua/gunit/main/testengine/sv_load.lua:78
         1. includeTests - addons/gwhat/lua/gunit/main/testengine/sv_load.lua:78
         2. load - addons/gwhat/lua/gunit/main/testengine/sv_load.lua:100
         3. unknown - lua/autorun/server/we.lua:6

And when running with the command 'test':

```
Running tests in every project.

Running tests for project: dankdata.
PlayerIdTable should:
+ add new players and select them
+ not add a player with the same SteamId to the table
+ get a whole row
+ update usernames
+ only update the specified user's name
+ get every player ID
PlayerPushKillTable should:
+ add a new player kill
Hooks should:
+ track player purchases
+ track when player DNA is found
- track when a player loots credits: *** FAILED ***
Error was: addons/dankdata/lua/ddd/main/overrides/sv_corpse.lua:11: attempt to call method 'GetNWString' (a nil value)
stack traceback:
        addons/dankdata/lua/ddd/main/overrides/sv_corpse.lua:11: in function 'GetPlayerSteamID'
        lua/../addons/dankdata/lua/ddd/test/hooks/sv_hooktest.lua:92: in function <lua/../addons/dankdata/lua/ddd/test/hooks/sv_hooktest.lua:81>
        [C]: in function 'xpcall'
        lua/../addons/gwhat/lua/gunit/main/testengine/sv_test.lua:93: in function 'runTestFunc'
        lua/../addons/gwhat/lua/gunit/main/testengine/sv_test.lua:106: in function 'runSpec'
        lua/../addons/gwhat/lua/gunit/main/testengine/sv_test.lua:133: in function 'runSpecs'
        addons/gwhat/lua/gunit/main/testengine/sv_runner.lua:62: in function 'runTest'
        addons/gwhat/lua/gunit/main/testengine/sv_runner.lua:69: in function 'runProjectTests'
        addons/gwhat/lua/gunit/main/testengine/sv_runner.lua:80: in function 'runAllTests'
        addons/gwhat/lua/gunit/main/testengine/sv_runner.lua:132: in funct
PurchaseTable should:
+ add a purchase by a player
* conform to constraints: * PENDING *
WorldDamageTable should:
+ add a damage log
* add a damage log if the attacker is 'worldspawn': * PENDING *
+ not add a damage if there is no rounds in the database
+ not add a damage log if the player does not exist
RadioCommandTable should:
+ add a command and select it
HealingTable should:
+ add a row with the correct amount a player healed
WeaponIdTable should:
+ add a weapon id and select it
+ not let you add an existing weapon
RadioCommandUsedTable should:
+ add rows from multiple players
+ add rows from multiple players targeting no one
+ add rows from multiple players targeting disguised people
+ add rows from multiple players targeting unidentified corpses
+ add rows from multiple players targeting identified corpses
* not add rows that do not have a player: * PENDING *
PlayerKillTable should:
+ add a new player kill
* get kills as a specific role: * PENDING *
* get suicides as a specific role: * PENDING *
RoundRoleTable should:
+ add a row containing the player's role that round
+ not allow you to add more than one role to a player per round
RoundIdTable should:
(09/17/16 04:24:38 PM) DDD[Error]: Could not insert into table test_1474122278_ddd_round_id!
        Error was:foreign key constraint failed
+ not allow rows to be added without any map ids
+ add a new, incrementing round every time the function is called
DnaTable should:
+ add new DNA discoveries
* fail to add DNA discoveries with no round ID: * PENDING *
MapIdTable should:
+ add the current map and select it
+ not automatically add the current map when copied
WorldKillTable should:
+ add rows properly

Running tests for project: gwhat.
FakePlayer should:
+ not break on creation
+ have non-nil SteamIDs
+ always generate the same SteamID
+ return a role with GetRole()

Running tests for project: autorun.
TestNameThatProbablyShouldntHaveSpacesAtThisTime: No tests to run.
Run completed in 5.062 seconds at 04:24:39 PM on Saturday, September 17, 2016
42 spec(s) run in 3 project(s). 35 passed, 1 failed, 6 pending.
Failed Test Suites:
dankdata::Hooks - 1 spec(s) failed.

```

**Comment by DarkRedemption** [comment] 2016-09-17 14:33
I'm guessing there's a severe difference in our environments causing problems. I'll try to replicate it. Make sure you're using the snapshot version of GUnit and sv_hibernate_think is set to 1.

**Comment by MinIsMin** [comment] 2016-09-17 14:38
OS: Ubuntu 14.04

```
Running tests in every project.

Running tests for project: nutnut.
FakePlayer should:
+ not break on creation
+ have non-nil SteamIDs
+ always generate the same SteamID
+ return a role with GetRole()

Running tests for project: autorun.
TestNameThatProbablyShouldntHaveSpacesAtThisTime: No tests to run.

Running tests for project: dankdata.
PlayerIdTable should:
+ add new players and select them
+ not add a player with the same SteamId to the table
+ get a whole row
+ update usernames
+ only update the specified user's name
+ get every player ID
PlayerPushKillTable should:
+ add a new player kill
Hooks should:
+ track player purchases
+ track when player DNA is found
+ track when a player loots credits
PurchaseTable should:
+ add a purchase by a player
* conform to constraints: * PENDING *
WorldDamageTable should:
+ add a damage log
* add a damage log if the attacker is 'worldspawn': * PENDING *
+ not add a damage if there is no rounds in the database
+ not add a damage log if the player does not exist
RadioCommandTable should:
+ add a command and select it
HealingTable should:
+ add a row with the correct amount a player healed
WeaponIdTable should:
+ add a weapon id and select it
+ not let you add an existing weapon
RadioCommandUsedTable should:
+ add rows from multiple players
+ add rows from multiple players targeting no one
+ add rows from multiple players targeting disguised people
+ add rows from multiple players targeting unidentified corpses
+ add rows from multiple players targeting identified corpses
* not add rows that do not have a player: * PENDING *
PlayerKillTable should:
+ add a new player kill
* get kills as a specific role: * PENDING *
* get suicides as a specific role: * PENDING *
RoundRoleTable should:
+ add a row containing the player's role that round
+ not allow you to add more than one role to a player per round
RoundIdTable should:
(09/17/16 04:37:28 PM) DDD[Error]: Could not insert into table test_1474123048_ddd_round_id!
        Error was:foreign key constraint failed
+ not allow rows to be added without any map ids
+ add a new, incrementing round every time the function is called
DnaTable should:
+ add new DNA discoveries
* fail to add DNA discoveries with no round ID: * PENDING *
MapIdTable should:
+ add the current map and select it
+ not automatically add the current map when copied
WorldKillTable should:
+ add rows properly
Run completed in 5.257 seconds at 04:37:30 PM on Saturday, September 17, 2016
42 spec(s) run in 3 project(s). 36 passed, 0 failed, 6 pending.
```

**Comment by DarkRedemption** [comment] 2016-09-17 14:48
Oh. Ubuntu. I haven't tried ubuntu. I'll make a VM and debug it.

**Comment by MinIsMin** [comment] 2016-09-17 14:50
Ubuntu is like any other Linux.
Most important thing: Only lower and no whitespaces in file and foldernames.

**Comment by DarkRedemption** [comment] 2016-09-17 16:07
No, I mean I only tried in Windows and not any Linux distro.

**Comment by DarkRedemption** [comment] 2016-09-18 13:58
I have confirmed that the problem is Linux at the moment, as I am getting the same issues in a VM of Ubuntu 16.04.1 LTE. Added issue #80.

**Comment by DarkRedemption** [comment] 2016-09-20 16:23
Seems to work for me now. I updated DDD and GUnit's SNAPSHOT versions, so try those now. Also, it looks like the server may need to run with elevated permissions--it needs enough to modify the SQLite database.

**Comment by MinIsMin** [comment] 2016-09-20 17:00
GUnit and DDD updated:

```
Running tests in every project.

Running tests for project: dankdata.
PlayerIdTable should:
+ add new players and select them
+ not add a player with the same SteamId to the table
+ get a whole row
+ update usernames
+ only update the specified user's name
+ get every player ID
RadioCommandTargetTable should:
+ add a live target
+ add a dead, identified target
PlayerPushKillTable should:
+ add a new player kill
Hooks should:
+ track player purchases
+ track when player DNA is found
+ track when a player loots credits
CombatHooks should:
+ track when a player dies from an attacker
+ track when a player dies from pushing
+ track when a player dies from the world
+ track when a player takes damage in combat
+ track when a player takes damage from the world
RankTable should:
* get the total enemy kd of each player properly: * PENDING *
PlayerStats should:
+ get the right number of rounds played in a role
* get the right number of assists in a role: * PENDING *
HealingTable should:
+ add a row with the correct amount a player healed
WorldKillTable should:
+ add rows properly
WorldDamageTable should:
+ add a damage log
* add a damage log if the attacker is 'worldspawn': * PENDING *
+ not add a damage if there is no rounds in the database
+ not add a damage log if the player does not exist
PurchaseTable should:
+ add a purchase by a player
* conform to constraints: * PENDING *
SimulatedRound should:
+ shuffle arrays
* find unique pairs in an array of players: * PENDING *
* find unique pairs in an array of players where a specific player is in each pair: * PENDING *
* have no kills from allied teams in a clean round: * PENDING *
AggregateStatsTable should:
+ add a player with no stats
+ increment rounds properly
+ increment rounds won properly
+ increment rounds lost properly
+ increment kills properly
+ increment deaths properly
+ increment suicides properly
+ increment world deaths properly
+ increment item purchases properly
+ increment c4 kills properly
+ increment healing properly
+ calculate a player's kills accurately
+ recalculate every player's stats who actually has no data
+ recalculate a player's rounds won
+ recalculate a player's rounds lost
+ recalculate every player's combat stats with data
+ recalculate every player's suicides with data
+ recalculate every player's world deaths with data
+ recalculate every player's purchases with data
+ recalculate every player's c4 kills with data
+ recalculate every player's healing stats with data
AggregateWeaponStatsTable: No tests to run.
MapIdTable should:
+ add the current map and select it
+ not automatically add the current map when copied
CreditsLootedTable should:
+ add credits looted
ForeignKeyTable: No tests to run.
ShopItemTable should:
+ add new items
RoundRoleTable should:
+ add a row containing the player's role that round
+ not allow you to add more than one role to a player per round
RoundResultTable should:
+ add a round result
+ not let you add more than one result per round
+ not let you add a result when there are no rounds
StatsActive should:
+ return true if everything is in order
+ return false if the population is less than what is defined in the config setting
+ return false if the map is blacklisted
+ return false if the round hasn't started
+ return true that the map is blacklisted if set as such in the config file
+ return true that population is too low if set as such in the config file
RoundIdTable should:
(09/20/16 06:53:05 PM) DDD[Error]: Could not insert into table test_1474390385_ddd_round_id!
        Error was:foreign key constraint failed
+ not allow rows to be added without any map ids
+ add a new, incrementing round every time the function is called
RadioCommandTable should:
+ add a command and select it
EntityTable should:
+ add new entities correctly
* get the entity id if it already exists: * PENDING *
WeaponIdTable should:
+ add a weapon id and select it
+ not let you add an existing weapon
RadioCommandUsedTable should:
+ add rows from multiple players
+ add rows from multiple players targeting no one
+ add rows from multiple players targeting disguised people
+ add rows from multiple players targeting unidentified corpses
+ add rows from multiple players targeting identified corpses
* not add rows that do not have a player: * PENDING *
PlayerKillTable should:
+ add a new player kill
* get kills as a specific role: * PENDING *
* get suicides as a specific role: * PENDING *
SqlTable should:
+ modify the tablename
+ create a table and add a row
+ select a known column
+ generate unique constraint queries correctly
CombatDamageTable should:
+ add damage logs to the table
DnaTable should:
+ add new DNA discoveries
* fail to add DNA discoveries with no round ID: * PENDING *
CorpseIdentifiedTable should:
+ add a found corpse
+ add a found corpse whose player has disconnected
ShotsFiredTable should:
+ add shots successfully
* fail if the player does not exist: * PENDING *
* fail if the weapon does not exist: * PENDING *
* fail if the attack type does not exist: * PENDING *

Running tests for project: guint.
String Generator should:
+ not break
+ stop the user from having a min size exceed the max size
AssertClass should:
+ perform shouldEqual properly with integers
+ perform shouldEqual properly with strings
+ perform lessThan properly with integers
+ perform lessThan properly with floats
+ perform lessThanOrEqualTo properly with integers
+ perform lessThanOrEqualTo properly with floats
+ perform greaterThan properly with integers
+ perform greaterThan properly with floats
+ perform greaterThanOrEqualTo properly with integers
+ perform greaterThanOrEqualTo properly with floats
+ perform isTrue properly
+ perform isFalse properly
+ chain together some asserts
FakePlayer should:
+ not break on creation
+ have non-nil SteamIDs
+ always generate the same SteamID
+ return a role with GetRole()
Test class should:
+ modify a value before any test starts (manually run this test twice to be sure it works)
+ modify a value before a spec starts
+ be sure that the value was reset, then run again
Run completed in 16.132 seconds at 06:53:09 PM on Tuesday, September 20, 2016
119 spec(s) run in 2 project(s). 104 passed, 0 failed, 15 pending.

```

SQLite should work without sudo rights and it works in other addons without sudo rights.
Is there a way to use PData? Or is it too complicated?

Lua errors when playing TTT:

[ULib] addons/dankdata/lua/ddd/main/hooks/sv_hooks.lua:141: attempt to call field 'TrackCreditsLooted' (a nil value)
1. fn - addons/dankdata/lua/ddd/main/hooks/sv_hooks.lua:141
   1. Call - lua/ulib/shared/hook.lua:110
   2. ShowSearch - addons/dankdata/lua/ddd/main/overrides/sv_corpse.lua:31
      1. unknown - gamemodes/terrortown/gamemode/player.lua:400

These errors stay:

[ERROR] addons/dankdata/lua/ddd/main/gui/rank/cl_overall.lua:25: bad argument #1 to 'pairs' (table expected, got number)
1. pairs - [C]:-1
   1. populateWithOverallEnemyKd - addons/dankdata/lua/ddd/main/gui/rank/cl_overall.lua:25
   2. updateListView - addons/dankdata/lua/ddd/main/gui/rank/cl_overall.lua:46
      1. OnSelect - addons/dankdata/lua/ddd/main/gui/rank/cl_overall.lua:77
      2. ChooseOption - lua/vgui/dcombobox.lua:108
      3. ChooseOptionID - lua/vgui/dcombobox.lua:118
      4. createOverallTab - addons/dankdata/lua/ddd/main/gui/rank/cl_overall.lua:81
         1. func - addons/dankdata/lua/ddd/main/gui/cl_mainpanel.lua:32
         2. unknown - lua/includes/extensions/net.lua:32

[ULib] addons/dankdata/lua/ddd/main/database/tables/sv_aggregatestats.lua:437: attempt to concatenate a nil value
1. getItemPurchases - addons/dankdata/lua/ddd/main/database/tables/sv_aggregatestats.lua:437
   1. incrementItemPurchases - addons/dankdata/lua/ddd/main/database/tables/sv_aggregatestats.lua:500
   2. trackPurchases - addons/dankdata/lua/ddd/main/hooks/sv_hooks.lua:24
      1. fn - addons/dankdata/lua/ddd/main/hooks/sv_hooks.lua:33
      2. Call - lua/ulib/shared/hook.lua:110
      3. unknown - gamemodes/terrortown/gamemode/weaponry.lua:421
      4. unknown - lua/includes/modules/concommand.lua:54

**Comment by DarkRedemption** [comment] 2016-09-20 17:24
If the tests run without elevated permissions successfully, then it can modify sv.db just fine. The tests make temporary SQL tables that are used only in the tests that are destroyed after the test completes, so they would fail if you couldn't get into sv.db. When I first ran it, it was saying it couldn't modify the SQL tables for some reason, so I wasn't sure if you'd need it or not.

Not sure about PData. Haven't tried it.

For the errors, I guess I'll have to play around in-game with the Linux server running and make new tests to check for these issues.

**Comment by MinIsMin** [comment] 2016-09-20 17:26
Thanks. PData can be an alternative for SQL storing, because Gmod saves (with the help of sqlite) the data in a user specific file.

**Comment by DarkRedemption** [comment] 2016-09-20 17:48
It looks like the remaining errors above are not Linux-based. The first is due to a brand-new feature I added recently and didn't thoroughly go over yet, i.e. wasn't production ready. The others appear to be errors caused by having a completely fresh database, which I didn't detect since I wasn't using one.

I already took down the first error. I'll be working on the other two either later today or tomorrow.

**Comment by DarkRedemption** [comment] 2016-09-21 14:25
It should work now. 

I wouldn't worry about the non-vanilla purchases error at the moment, by the way. What's happening there is that the purchase is actually being logged, but that's because the purchases table in the database doesn't use the name of the purchase as a column, just a value. AggregateStats uses a column for every individual thing it tracks for a single player, and the column for that purchase is not made.

This is why, for weapons, I'm working on tracking the number of kills/shots fired in the AggregateStats table (or AggregateWeaponStats table) by dynamically determining what columns need to be made by getting a list of weapons as the table is being created. I intend to do the same thing for purchasable items, if possible, and then that issue will be solved.

But for now, it shouldn't cause any issues and the stats will still technically be tracked.

**Comment by MinIsMin** [comment] 2016-09-21 14:39
Looks good. Is there a way to exclude Bots (normal TTT Bots) from the Rank and user(/bot) statistics?
I use them for testing purposes.

**Comment by DarkRedemption** [comment] 2016-09-21 15:02
Not at this time. I too use them for testing purposes, but on a local test server, so it never mattered much to me. In production, if you happened to spawn bots, the only ranks that will likely be shown for them is that of Round Played--which will eventually be hidden once you've had >25 players on your server. So the only really issue is accidentally padding/ruining stats via bots.

If you want to manually delete bot stats, just find their ID in the ddd_player_id table, delete all references to that ID, then delete that entry.

**Closed as completed** 2016-09-22 00:16 UTC
